{
  imports = [
    ./grub.nix
    ./settings.nix
    ./access-tokens.nix
    ./networking.nix
    ./power.nix
    ./sound.nix
    ./environment.nix
    ./fonts.nix
    ./localization.nix
    ./pkgs.nix
    ./nvidia.nix
    ./rime.nix
    ./dae.nix
    ./kde.nix
    ./cleaner.nix
    ./steam.nix
  ];
}
